// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: coming.proto

package coming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ComingServiceClient is the client API for ComingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComingServiceClient interface {
	GetAll(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
	GetById(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Coming, error)
	Create(ctx context.Context, in *ComingCreate, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *Coming, opts ...grpc.CallOption) (*Response, error)
	SdelatPrihod(ctx context.Context, in *Zavershit, opts ...grpc.CallOption) (*Response, error)
}

type comingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComingServiceClient(cc grpc.ClientConnInterface) ComingServiceClient {
	return &comingServiceClient{cc}
}

func (c *comingServiceClient) GetAll(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/coming.ComingService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comingServiceClient) GetById(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Coming, error) {
	out := new(Coming)
	err := c.cc.Invoke(ctx, "/coming.ComingService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comingServiceClient) Create(ctx context.Context, in *ComingCreate, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/coming.ComingService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comingServiceClient) Delete(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/coming.ComingService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comingServiceClient) Update(ctx context.Context, in *Coming, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/coming.ComingService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comingServiceClient) SdelatPrihod(ctx context.Context, in *Zavershit, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/coming.ComingService/SdelatPrihod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComingServiceServer is the server API for ComingService service.
// All implementations must embed UnimplementedComingServiceServer
// for forward compatibility
type ComingServiceServer interface {
	GetAll(context.Context, *GetListRequest) (*GetListResponse, error)
	GetById(context.Context, *Pkey) (*Coming, error)
	Create(context.Context, *ComingCreate) (*Response, error)
	Delete(context.Context, *Pkey) (*Response, error)
	Update(context.Context, *Coming) (*Response, error)
	SdelatPrihod(context.Context, *Zavershit) (*Response, error)
	mustEmbedUnimplementedComingServiceServer()
}

// UnimplementedComingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedComingServiceServer struct {
}

func (UnimplementedComingServiceServer) GetAll(context.Context, *GetListRequest) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedComingServiceServer) GetById(context.Context, *Pkey) (*Coming, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedComingServiceServer) Create(context.Context, *ComingCreate) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedComingServiceServer) Delete(context.Context, *Pkey) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedComingServiceServer) Update(context.Context, *Coming) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedComingServiceServer) SdelatPrihod(context.Context, *Zavershit) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SdelatPrihod not implemented")
}
func (UnimplementedComingServiceServer) mustEmbedUnimplementedComingServiceServer() {}

// UnsafeComingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComingServiceServer will
// result in compilation errors.
type UnsafeComingServiceServer interface {
	mustEmbedUnimplementedComingServiceServer()
}

func RegisterComingServiceServer(s grpc.ServiceRegistrar, srv ComingServiceServer) {
	s.RegisterService(&ComingService_ServiceDesc, srv)
}

func _ComingService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComingServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coming.ComingService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComingServiceServer).GetAll(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComingService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComingServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coming.ComingService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComingServiceServer).GetById(ctx, req.(*Pkey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComingService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComingCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComingServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coming.ComingService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComingServiceServer).Create(ctx, req.(*ComingCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComingService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComingServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coming.ComingService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComingServiceServer).Delete(ctx, req.(*Pkey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComingService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Coming)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComingServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coming.ComingService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComingServiceServer).Update(ctx, req.(*Coming))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComingService_SdelatPrihod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Zavershit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComingServiceServer).SdelatPrihod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coming.ComingService/SdelatPrihod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComingServiceServer).SdelatPrihod(ctx, req.(*Zavershit))
	}
	return interceptor(ctx, in, info, handler)
}

// ComingService_ServiceDesc is the grpc.ServiceDesc for ComingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coming.ComingService",
	HandlerType: (*ComingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _ComingService_GetAll_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _ComingService_GetById_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ComingService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ComingService_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ComingService_Update_Handler,
		},
		{
			MethodName: "SdelatPrihod",
			Handler:    _ComingService_SdelatPrihod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coming.proto",
}

// ComingProductsServiceClient is the client API for ComingProductsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComingProductsServiceClient interface {
	GetAll(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponseComingProducts, error)
	GetById(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*ComingProducts, error)
	Create(ctx context.Context, in *ComingProductsCreate, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *ComingProducts, opts ...grpc.CallOption) (*Response, error)
}

type comingProductsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComingProductsServiceClient(cc grpc.ClientConnInterface) ComingProductsServiceClient {
	return &comingProductsServiceClient{cc}
}

func (c *comingProductsServiceClient) GetAll(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponseComingProducts, error) {
	out := new(GetListResponseComingProducts)
	err := c.cc.Invoke(ctx, "/coming.ComingProductsService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comingProductsServiceClient) GetById(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*ComingProducts, error) {
	out := new(ComingProducts)
	err := c.cc.Invoke(ctx, "/coming.ComingProductsService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comingProductsServiceClient) Create(ctx context.Context, in *ComingProductsCreate, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/coming.ComingProductsService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comingProductsServiceClient) Delete(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/coming.ComingProductsService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comingProductsServiceClient) Update(ctx context.Context, in *ComingProducts, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/coming.ComingProductsService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComingProductsServiceServer is the server API for ComingProductsService service.
// All implementations must embed UnimplementedComingProductsServiceServer
// for forward compatibility
type ComingProductsServiceServer interface {
	GetAll(context.Context, *GetListRequest) (*GetListResponseComingProducts, error)
	GetById(context.Context, *Pkey) (*ComingProducts, error)
	Create(context.Context, *ComingProductsCreate) (*Response, error)
	Delete(context.Context, *Pkey) (*Response, error)
	Update(context.Context, *ComingProducts) (*Response, error)
	mustEmbedUnimplementedComingProductsServiceServer()
}

// UnimplementedComingProductsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedComingProductsServiceServer struct {
}

func (UnimplementedComingProductsServiceServer) GetAll(context.Context, *GetListRequest) (*GetListResponseComingProducts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedComingProductsServiceServer) GetById(context.Context, *Pkey) (*ComingProducts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedComingProductsServiceServer) Create(context.Context, *ComingProductsCreate) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedComingProductsServiceServer) Delete(context.Context, *Pkey) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedComingProductsServiceServer) Update(context.Context, *ComingProducts) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedComingProductsServiceServer) mustEmbedUnimplementedComingProductsServiceServer() {}

// UnsafeComingProductsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComingProductsServiceServer will
// result in compilation errors.
type UnsafeComingProductsServiceServer interface {
	mustEmbedUnimplementedComingProductsServiceServer()
}

func RegisterComingProductsServiceServer(s grpc.ServiceRegistrar, srv ComingProductsServiceServer) {
	s.RegisterService(&ComingProductsService_ServiceDesc, srv)
}

func _ComingProductsService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComingProductsServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coming.ComingProductsService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComingProductsServiceServer).GetAll(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComingProductsService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComingProductsServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coming.ComingProductsService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComingProductsServiceServer).GetById(ctx, req.(*Pkey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComingProductsService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComingProductsCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComingProductsServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coming.ComingProductsService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComingProductsServiceServer).Create(ctx, req.(*ComingProductsCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComingProductsService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComingProductsServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coming.ComingProductsService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComingProductsServiceServer).Delete(ctx, req.(*Pkey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComingProductsService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComingProducts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComingProductsServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coming.ComingProductsService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComingProductsServiceServer).Update(ctx, req.(*ComingProducts))
	}
	return interceptor(ctx, in, info, handler)
}

// ComingProductsService_ServiceDesc is the grpc.ServiceDesc for ComingProductsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComingProductsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coming.ComingProductsService",
	HandlerType: (*ComingProductsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _ComingProductsService_GetAll_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _ComingProductsService_GetById_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ComingProductsService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ComingProductsService_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ComingProductsService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coming.proto",
}
