// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: change.proto

package change

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChangeServiceClient is the client API for ChangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChangeServiceClient interface {
	GetAll(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
	GetById(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Change, error)
	Create(ctx context.Context, in *ChangeCreate, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *Change, opts ...grpc.CallOption) (*Response, error)
	OpenChange(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Response, error)
	CloseChange(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Response, error)
}

type changeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChangeServiceClient(cc grpc.ClientConnInterface) ChangeServiceClient {
	return &changeServiceClient{cc}
}

func (c *changeServiceClient) GetAll(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/change.ChangeService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) GetById(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Change, error) {
	out := new(Change)
	err := c.cc.Invoke(ctx, "/change.ChangeService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) Create(ctx context.Context, in *ChangeCreate, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/change.ChangeService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) Delete(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/change.ChangeService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) Update(ctx context.Context, in *Change, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/change.ChangeService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) OpenChange(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/change.ChangeService/OpenChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) CloseChange(ctx context.Context, in *Pkey, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/change.ChangeService/CloseChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChangeServiceServer is the server API for ChangeService service.
// All implementations must embed UnimplementedChangeServiceServer
// for forward compatibility
type ChangeServiceServer interface {
	GetAll(context.Context, *GetListRequest) (*GetListResponse, error)
	GetById(context.Context, *Pkey) (*Change, error)
	Create(context.Context, *ChangeCreate) (*Response, error)
	Delete(context.Context, *Pkey) (*Response, error)
	Update(context.Context, *Change) (*Response, error)
	OpenChange(context.Context, *Pkey) (*Response, error)
	CloseChange(context.Context, *Pkey) (*Response, error)
	mustEmbedUnimplementedChangeServiceServer()
}

// UnimplementedChangeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChangeServiceServer struct {
}

func (UnimplementedChangeServiceServer) GetAll(context.Context, *GetListRequest) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedChangeServiceServer) GetById(context.Context, *Pkey) (*Change, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedChangeServiceServer) Create(context.Context, *ChangeCreate) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedChangeServiceServer) Delete(context.Context, *Pkey) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedChangeServiceServer) Update(context.Context, *Change) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedChangeServiceServer) OpenChange(context.Context, *Pkey) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenChange not implemented")
}
func (UnimplementedChangeServiceServer) CloseChange(context.Context, *Pkey) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseChange not implemented")
}
func (UnimplementedChangeServiceServer) mustEmbedUnimplementedChangeServiceServer() {}

// UnsafeChangeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChangeServiceServer will
// result in compilation errors.
type UnsafeChangeServiceServer interface {
	mustEmbedUnimplementedChangeServiceServer()
}

func RegisterChangeServiceServer(s grpc.ServiceRegistrar, srv ChangeServiceServer) {
	s.RegisterService(&ChangeService_ServiceDesc, srv)
}

func _ChangeService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/change.ChangeService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).GetAll(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/change.ChangeService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).GetById(ctx, req.(*Pkey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/change.ChangeService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).Create(ctx, req.(*ChangeCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/change.ChangeService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).Delete(ctx, req.(*Pkey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Change)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/change.ChangeService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).Update(ctx, req.(*Change))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_OpenChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).OpenChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/change.ChangeService/OpenChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).OpenChange(ctx, req.(*Pkey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_CloseChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).CloseChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/change.ChangeService/CloseChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).CloseChange(ctx, req.(*Pkey))
	}
	return interceptor(ctx, in, info, handler)
}

// ChangeService_ServiceDesc is the grpc.ServiceDesc for ChangeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChangeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "change.ChangeService",
	HandlerType: (*ChangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _ChangeService_GetAll_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _ChangeService_GetById_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ChangeService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ChangeService_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ChangeService_Update_Handler,
		},
		{
			MethodName: "OpenChange",
			Handler:    _ChangeService_OpenChange_Handler,
		},
		{
			MethodName: "CloseChange",
			Handler:    _ChangeService_CloseChange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "change.proto",
}
